# Generated by Django 5.2.1 on 2025-05-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trekking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtrek',
            name='event_status',
            field=models.CharField(choices=[('PIANIFICATO', 'Pianificato'), ('CONFERMATO', 'Confermato'), ('ANNULLATO_METEO', 'Annullato (Meteo)'), ('ANNULLATO_ORGANIZZATORE', 'Annullato (Organizzatore)'), ('COMPLETATO', 'Completato')], default='PIANIFICATO', max_length=30, verbose_name='Stato Uscita'),
        ),
        migrations.AddField(
            model_name='trek',
            name='estimated_duration_hours',
            field=models.FloatField(blank=True, help_text='Solo numero, es. 3.5 per 3 ore e mezza. Utile per calcoli.', null=True, verbose_name='Durata Stimata (ore numerico)'),
        ),
        migrations.AlterField(
            model_name='scheduledtrek',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Indica se l'uscita deve apparire nelle liste pubbliche delle prossime uscite. Impostare a No per uscite annullate o completate.", verbose_name='Visibile Pubblicamente'),
        ),
        migrations.AlterField(
            model_name='trekregistration',
            name='status',
            field=models.CharField(choices=[('CONFERMATA', 'Confermata'), ('ANNULLATA_UTENTE', 'Annullata (Utente)'), ('ANNULLATA_ADMIN', 'Annullata (Admin)'), ('COMPLETATA', 'Completata')], default='CONFERMATA', max_length=20, verbose_name='Stato Iscrizione'),
        ),
    ]
