# Generated by Django 5.2.1 on 2025-05-19 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trekking', '0002_scheduledtrek_event_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtrek',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, help_text="Opzionale: specifica data e ora esatta di chiusura. Se non impostato, le iscrizioni chiudono con l'inizio dell'evento o se 'Iscrizioni Aperte' è deselezionato.", null=True, verbose_name='Termine Iscrizioni'),
        ),
        migrations.AlterField(
            model_name='scheduledtrek',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Controlla la visibilità nelle liste di uscite future attive. Viene gestito anche dal metodo save() in base allo stato.', verbose_name='Visibile Pubblicamente nelle Liste Future'),
        ),
        migrations.AlterField(
            model_name='scheduledtrek',
            name='registration_open',
            field=models.BooleanField(default=True, verbose_name='Iscrizioni Aperte (Manuale)'),
        ),
        migrations.AlterField(
            model_name='scheduledtrek',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Orario di Ritrovo'),
        ),
        migrations.AlterField(
            model_name='trekregistration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utente Registrato'),
        ),
    ]
