# Generated by Django 5.2.1 on 2025-05-21 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trekking', '0003_scheduledtrek_registration_deadline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trekregistration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='trekregistration',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Indirizzo di Residenza (Via, N°)'),
        ),
        migrations.AddField(
            model_name='trekregistration',
            name='available_seats',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='N° Posti Auto Disponibili (oltre al guidatore)'),
        ),
        migrations.AddField(
            model_name='trekregistration',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data di Nascita'),
        ),
        migrations.AddField(
            model_name='trekregistration',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Luogo di Nascita'),
        ),
        migrations.AddField(
            model_name='trekregistration',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Città di Residenza'),
        ),
        migrations.AddField(
            model_name='trekregistration',
            name='fiscal_code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Codice Fiscale'),
        ),
        migrations.AddField(
            model_name='trekregistration',
            name='has_car',
            field=models.BooleanField(default=False, verbose_name='Disponibilità Auto?'),
        ),
        migrations.AddField(
            model_name='trekregistration',
            name='is_member',
            field=models.BooleanField(default=False, verbose_name="È Socio de 'La Company'?"),
        ),
        migrations.AddField(
            model_name='trekregistration',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CAP'),
        ),
        migrations.AlterField(
            model_name='trekregistration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utente Registrato (se loggato)'),
        ),
    ]
